package redis.clients.jedis;

import java.util.EnumSet;
import redis.clients.jedis.args.Rawable;
import redis.clients.jedis.commands.ProtocolCommand;
import redis.clients.jedis.util.JedisByteMap;
import redis.clients.jedis.util.SafeEncoder;

/**
 * Static implementation of CommandFlagsRegistry. This class is auto-generated by
 * CommandFlagsRegistryGenerator. DO NOT EDIT MANUALLY.
 * <p>Generated from Redis Server:
 * <ul>
 * <li>Version: 8.2.3</li>
 * <li>Mode: standalone</li>
 * <li>Loaded Modules: ReJSON, timeseries, bf, vectorset, search</li>
 * <li>Generated at: 2025-11-04 13:00:13 CET</li>
 * </ul>
 */
public class StaticCommandFlagsRegistry implements CommandFlagsRegistry {

  // Empty flags constant for commands with no flags
  private static final EnumSet<CommandFlag> EMPTY_FLAGS = EnumSet.noneOf(CommandFlag.class);

  // Hierarchical command flags registry using byte arrays as keys
  // Maps parent command names (as uppercase byte arrays) to their flags and subcommands
  // For simple commands (no subcommands), the parent command maps directly to flags
  // For parent commands with subcommands, the parent maps to a SubcommandRegistry
  // Using JedisByteMap avoids String conversion during lookup, providing ~2.5x performance improvement
  private static final JedisByteMap<Object> COMMAND_FLAGS_REGISTRY = new JedisByteMap<>();

  /**
   * Internal class to hold subcommand mappings for parent commands.
   * Uses JedisByteMap for faster subcommand lookup without String conversion.
   */
  private static class SubcommandRegistry {
    final EnumSet<CommandFlag> parentFlags;
    final JedisByteMap<EnumSet<CommandFlag>> subcommands;

    SubcommandRegistry(EnumSet<CommandFlag> parentFlags) {
      this.parentFlags = parentFlags;
      this.subcommands = new JedisByteMap<>();
    }
  }

  static {
    // ACL parent command with subcommands
    SubcommandRegistry aclRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    aclRegistry.subcommands.put(SafeEncoder.encode("CAT"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("DELUSER"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("DRYRUN"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("GENPASS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("GETUSER"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("LIST"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("LOAD"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("LOG"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("SAVE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("SETUSER"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("USERS"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    aclRegistry.subcommands.put(SafeEncoder.encode("WHOAMI"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ACL"), aclRegistry);

    // OBJECT parent command with subcommands
    SubcommandRegistry objectRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    objectRegistry.subcommands.put(SafeEncoder.encode("ENCODING"), EnumSet.of(CommandFlag.READONLY));
    objectRegistry.subcommands.put(SafeEncoder.encode("FREQ"), EnumSet.of(CommandFlag.READONLY));
    objectRegistry.subcommands.put(SafeEncoder.encode("IDLETIME"), EnumSet.of(CommandFlag.READONLY));
    objectRegistry.subcommands.put(SafeEncoder.encode("REFCOUNT"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("OBJECT"), objectRegistry);

    // FUNCTION parent command with subcommands
    SubcommandRegistry functionRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    functionRegistry.subcommands.put(SafeEncoder.encode("DELETE"), EnumSet.of(CommandFlag.NOSCRIPT, CommandFlag.WRITE));
    functionRegistry.subcommands.put(SafeEncoder.encode("DUMP"), EnumSet.of(CommandFlag.NOSCRIPT));
    functionRegistry.subcommands.put(SafeEncoder.encode("FLUSH"), EnumSet.of(CommandFlag.NOSCRIPT, CommandFlag.WRITE));
    functionRegistry.subcommands.put(SafeEncoder.encode("KILL"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.NOSCRIPT));
    functionRegistry.subcommands.put(SafeEncoder.encode("LIST"), EnumSet.of(CommandFlag.NOSCRIPT));
    functionRegistry.subcommands.put(SafeEncoder.encode("LOAD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.NOSCRIPT, CommandFlag.WRITE));
    functionRegistry.subcommands.put(SafeEncoder.encode("RESTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.NOSCRIPT, CommandFlag.WRITE));
    functionRegistry.subcommands.put(SafeEncoder.encode("STATS"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.NOSCRIPT));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FUNCTION"), functionRegistry);

    // CLIENT parent command with subcommands
    SubcommandRegistry clientRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    clientRegistry.subcommands.put(SafeEncoder.encode("CACHING"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("GETNAME"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("GETREDIR"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("ID"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("INFO"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("KILL"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("LIST"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("NO-EVICT"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("NO-TOUCH"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("PAUSE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("REPLY"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("SETINFO"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("SETNAME"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("TRACKING"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("TRACKINGINFO"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("UNBLOCK"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clientRegistry.subcommands.put(SafeEncoder.encode("UNPAUSE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CLIENT"), clientRegistry);

    // CONFIG parent command with subcommands
    SubcommandRegistry configRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    configRegistry.subcommands.put(SafeEncoder.encode("GET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    configRegistry.subcommands.put(SafeEncoder.encode("RESETSTAT"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    configRegistry.subcommands.put(SafeEncoder.encode("REWRITE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    configRegistry.subcommands.put(SafeEncoder.encode("SET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CONFIG"), configRegistry);

    // MODULE parent command with subcommands
    SubcommandRegistry moduleRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    moduleRegistry.subcommands.put(SafeEncoder.encode("LIST"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT));
    moduleRegistry.subcommands.put(SafeEncoder.encode("LOAD"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING));
    moduleRegistry.subcommands.put(SafeEncoder.encode("LOADEX"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING));
    moduleRegistry.subcommands.put(SafeEncoder.encode("UNLOAD"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MODULE"), moduleRegistry);

    // PUBSUB parent command with subcommands
    SubcommandRegistry pubsubRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    pubsubRegistry.subcommands.put(SafeEncoder.encode("CHANNELS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));
    pubsubRegistry.subcommands.put(SafeEncoder.encode("NUMPAT"), EnumSet.of(CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));
    pubsubRegistry.subcommands.put(SafeEncoder.encode("NUMSUB"), EnumSet.of(CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));
    pubsubRegistry.subcommands.put(SafeEncoder.encode("SHARDCHANNELS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));
    pubsubRegistry.subcommands.put(SafeEncoder.encode("SHARDNUMSUB"), EnumSet.of(CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PUBSUB"), pubsubRegistry);

    // SCRIPT parent command with subcommands
    SubcommandRegistry scriptRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    scriptRegistry.subcommands.put(SafeEncoder.encode("DEBUG"), EnumSet.of(CommandFlag.NOSCRIPT));
    scriptRegistry.subcommands.put(SafeEncoder.encode("EXISTS"), EnumSet.of(CommandFlag.NOSCRIPT));
    scriptRegistry.subcommands.put(SafeEncoder.encode("FLUSH"), EnumSet.of(CommandFlag.NOSCRIPT));
    scriptRegistry.subcommands.put(SafeEncoder.encode("KILL"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.NOSCRIPT));
    scriptRegistry.subcommands.put(SafeEncoder.encode("LOAD"), EnumSet.of(CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SCRIPT"), scriptRegistry);

    // MEMORY parent command with subcommands
    SubcommandRegistry memoryRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    memoryRegistry.subcommands.put(SafeEncoder.encode("DOCTOR"), EMPTY_FLAGS);
    memoryRegistry.subcommands.put(SafeEncoder.encode("MALLOC-STATS"), EMPTY_FLAGS);
    memoryRegistry.subcommands.put(SafeEncoder.encode("PURGE"), EMPTY_FLAGS);
    memoryRegistry.subcommands.put(SafeEncoder.encode("STATS"), EMPTY_FLAGS);
    memoryRegistry.subcommands.put(SafeEncoder.encode("USAGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MEMORY"), memoryRegistry);

    // SLOWLOG parent command with subcommands
    SubcommandRegistry slowlogRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    slowlogRegistry.subcommands.put(SafeEncoder.encode("GET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.STALE));
    slowlogRegistry.subcommands.put(SafeEncoder.encode("LEN"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.STALE));
    slowlogRegistry.subcommands.put(SafeEncoder.encode("RESET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SLOWLOG"), slowlogRegistry);

    // COMMAND parent command with subcommands
    SubcommandRegistry commandRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    commandRegistry.subcommands.put(SafeEncoder.encode("COUNT"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    commandRegistry.subcommands.put(SafeEncoder.encode("DOCS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    commandRegistry.subcommands.put(SafeEncoder.encode("GETKEYS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    commandRegistry.subcommands.put(SafeEncoder.encode("GETKEYSANDFLAGS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    commandRegistry.subcommands.put(SafeEncoder.encode("INFO"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    commandRegistry.subcommands.put(SafeEncoder.encode("LIST"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("COMMAND"), commandRegistry);

    // LATENCY parent command with subcommands
    SubcommandRegistry latencyRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    latencyRegistry.subcommands.put(SafeEncoder.encode("DOCTOR"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    latencyRegistry.subcommands.put(SafeEncoder.encode("GRAPH"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    latencyRegistry.subcommands.put(SafeEncoder.encode("HISTOGRAM"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    latencyRegistry.subcommands.put(SafeEncoder.encode("HISTORY"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    latencyRegistry.subcommands.put(SafeEncoder.encode("LATEST"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    latencyRegistry.subcommands.put(SafeEncoder.encode("RESET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LATENCY"), latencyRegistry);

    // CLUSTER parent command with subcommands
    SubcommandRegistry clusterRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    clusterRegistry.subcommands.put(SafeEncoder.encode("ADDSLOTS"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("ADDSLOTSRANGE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("BUMPEPOCH"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("COUNT-FAILURE-REPORTS"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("COUNTKEYSINSLOT"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("DELSLOTS"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("DELSLOTSRANGE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("FAILOVER"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("FLUSHSLOTS"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("FORGET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("GETKEYSINSLOT"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("INFO"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("KEYSLOT"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("LINKS"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("MEET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("MYID"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("MYSHARDID"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("NODES"), EnumSet.of(CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("REPLICAS"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("REPLICATE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("RESET"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SAVECONFIG"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SET-CONFIG-EPOCH"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SETSLOT"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SHARDS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SLAVES"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SLOT-STATS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    clusterRegistry.subcommands.put(SafeEncoder.encode("SLOTS"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CLUSTER"), clusterRegistry);

    // XINFO parent command with subcommands
    SubcommandRegistry xinfoRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    xinfoRegistry.subcommands.put(SafeEncoder.encode("CONSUMERS"), EnumSet.of(CommandFlag.READONLY));
    xinfoRegistry.subcommands.put(SafeEncoder.encode("GROUPS"), EnumSet.of(CommandFlag.READONLY));
    xinfoRegistry.subcommands.put(SafeEncoder.encode("STREAM"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XINFO"), xinfoRegistry);

    // XGROUP parent command with subcommands
    SubcommandRegistry xgroupRegistry = new SubcommandRegistry(EMPTY_FLAGS);
    xgroupRegistry.subcommands.put(SafeEncoder.encode("CREATE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    xgroupRegistry.subcommands.put(SafeEncoder.encode("CREATECONSUMER"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    xgroupRegistry.subcommands.put(SafeEncoder.encode("DELCONSUMER"), EnumSet.of(CommandFlag.WRITE));
    xgroupRegistry.subcommands.put(SafeEncoder.encode("DESTROY"), EnumSet.of(CommandFlag.WRITE));
    xgroupRegistry.subcommands.put(SafeEncoder.encode("SETID"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XGROUP"), xgroupRegistry);

    // 1 command(s) with: admin
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PFSELFTEST"), EnumSet.of(CommandFlag.ADMIN));

    // 2 command(s) with: blocking
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("WAIT"), EnumSet.of(CommandFlag.BLOCKING));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("WAITAOF"), EnumSet.of(CommandFlag.BLOCKING));

    // 2 command(s) with: fast
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ASKING"), EnumSet.of(CommandFlag.FAST));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PING"), EnumSet.of(CommandFlag.FAST));

    // 41 command(s) with: readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BITCOUNT"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BITPOS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DUMP"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEODIST"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEOHASH"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEOPOS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEORADIUSBYMEMBER_RO"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEORADIUS_RO"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEOSEARCH"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GETRANGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HGETALL"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HKEYS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HRANDFIELD"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HSCAN"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HVALS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("KEYS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LCS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LINDEX"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LPOS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LRANGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PFCOUNT"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RANDOMKEY"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SCAN"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SDIFF"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SINTER"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SMEMBERS"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SRANDMEMBER"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SSCAN"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SUBSTR"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SUNION"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XPENDING"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XRANGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XREVRANGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZRANDMEMBER"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZRANGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZRANGEBYLEX"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZRANGEBYSCORE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREVRANGE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREVRANGEBYLEX"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREVRANGEBYSCORE"), EnumSet.of(CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZSCAN"), EnumSet.of(CommandFlag.READONLY));

    // 10 command(s) with: write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DEL"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FLUSHALL"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FLUSHDB"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LREM"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LTRIM"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RENAME"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XTRIM"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREMRANGEBYLEX"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREMRANGEBYRANK"), EnumSet.of(CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREMRANGEBYSCORE"), EnumSet.of(CommandFlag.WRITE));

    // 2 command(s) with: blocking, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BLPOP"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BRPOP"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.WRITE));

    // 22 command(s) with: denyoom, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BITFIELD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BITOP"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("COPY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEOADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEOSEARCHSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LINSERT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LMOVE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LSET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MSET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MSETNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PFMERGE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PSETEX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RESTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RPOPLPUSH"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SDIFFSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SETBIT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SETEX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SETRANGE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SINTERSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SUNIONSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZRANGESTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.WRITE));

    // 35 command(s) with: fast, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BITFIELD_RO"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DBSIZE"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EXISTS"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EXPIRETIME"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GET"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GETBIT"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HEXISTS"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HEXPIRETIME"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HGET"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HLEN"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HMGET"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HPEXPIRETIME"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HPTTL"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HSTRLEN"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HTTL"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LLEN"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LOLWUT"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MGET"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PEXPIRETIME"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PTTL"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SCARD"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SISMEMBER"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SMISMEMBER"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("STRLEN"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOUCH"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TTL"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TYPE"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XLEN"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZCARD"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZCOUNT"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZLEXCOUNT"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZMSCORE"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZRANK"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREVRANK"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZSCORE"), EnumSet.of(CommandFlag.FAST, CommandFlag.READONLY));

    // 33 command(s) with: fast, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EXPIRE"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EXPIREAT"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GETDEL"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GETEX"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HDEL"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HEXPIRE"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HEXPIREAT"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HGETDEL"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HGETEX"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HPERSIST"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HPEXPIRE"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HPEXPIREAT"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LPOP"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MOVE"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PERSIST"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PEXPIRE"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PEXPIREAT"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RENAMENX"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RPOP"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SMOVE"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SPOP"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SREM"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SWAPDB"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("UNLINK"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XACK"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XACKDEL"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XAUTOCLAIM"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XCLAIM"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XDEL"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XDELEX"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZPOPMAX"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZPOPMIN"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZREM"), EnumSet.of(CommandFlag.FAST, CommandFlag.WRITE));

    // 1 command(s) with: loading, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("INFO"), EnumSet.of(CommandFlag.LOADING, CommandFlag.STALE));

    // 55 command(s) with: module, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CMS.INFO"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CMS.QUERY"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.AGGREGATE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.CONFIG"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.CURSOR"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.DICTDUMP"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.EXPLAIN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.EXPLAINCLI"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.GET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.INFO"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.MGET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.PROFILE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SEARCH"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SPELLCHECK"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SUGGET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SUGLEN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SYNDUMP"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.TAGVALS"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._LIST"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.ARRINDEX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.ARRLEN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.DEBUG"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.GET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.MGET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.OBJKEYS"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.OBJLEN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.RESP"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.STRLEN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.TYPE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.BYRANK"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.BYREVRANK"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.CDF"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.INFO"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.MAX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.MIN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.QUANTILE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.RANK"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.REVRANK"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.TRIMMED_MEAN"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.COUNT"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.INFO"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.LIST"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.QUERY"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.GET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.INFO"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.MGET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.MRANGE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.MREVRANGE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.QUERYINDEX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.RANGE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.REVRANGE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VISMEMBER"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VRANDMEMBER"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VSIM"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("_FT.CONFIG"), EnumSet.of(CommandFlag.MODULE, CommandFlag.READONLY));

    // 20 command(s) with: module, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.ALIASDEL"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.DEL"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.DICTDEL"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.DROP"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.DROPINDEX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SUGDEL"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._ALIASDELIFX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._DROPIFX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._DROPINDEXIFX"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.ARRPOP"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.ARRTRIM"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.CLEAR"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.DEL"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.FORGET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.NUMINCRBY"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.NUMMULTBY"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.NUMPOWBY"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.DEL"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.DELETERULE"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VREM"), EnumSet.of(CommandFlag.MODULE, CommandFlag.WRITE));

    // 6 command(s) with: movablekeys, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SINTERCARD"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SORT_RO"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZDIFF"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZINTER"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZINTERCARD"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZUNION"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));

    // 3 command(s) with: movablekeys, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LMPOP"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MIGRATE"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZMPOP"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));

    // 1 command(s) with: admin, denyoom, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PFDEBUG"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.DENYOOM, CommandFlag.WRITE));

    // 2 command(s) with: admin, noscript, no_async_loading
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BGREWRITEAOF"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BGSAVE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING));

    // 1 command(s) with: admin, noscript, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FAILOVER"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.STALE));

    // 1 command(s) with: asking, denyoom, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RESTORE-ASKING"), EnumSet.of(CommandFlag.ASKING, CommandFlag.DENYOOM, CommandFlag.WRITE));

    // 2 command(s) with: blocking, denyoom, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BLMOVE"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.DENYOOM, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BRPOPLPUSH"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.DENYOOM, CommandFlag.WRITE));

    // 2 command(s) with: blocking, fast, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BZPOPMAX"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BZPOPMIN"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.FAST, CommandFlag.WRITE));

    // 1 command(s) with: blocking, movablekeys, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XREAD"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.MOVABLEKEYS, CommandFlag.READONLY));

    // 3 command(s) with: blocking, movablekeys, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BLMPOP"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BZMPOP"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XREADGROUP"), EnumSet.of(CommandFlag.BLOCKING, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));

    // 24 command(s) with: denyoom, fast, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("APPEND"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DECR"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DECRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GETSET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HINCRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HINCRBYFLOAT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HMSET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HSET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HSETEX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HSETNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("INCR"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("INCRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("INCRBYFLOAT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LPUSH"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LPUSHX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PFADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RPUSH"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RPUSHX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SETNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("XSETID"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZINCRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.FAST, CommandFlag.WRITE));

    // 49 command(s) with: denyoom, module, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.ADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.INSERT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.LOADCHUNK"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.MADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.RESERVE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.ADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.ADDNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.INSERT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.INSERTNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.LOADCHUNK"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.RESERVE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CMS.INCRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CMS.INITBYDIM"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CMS.INITBYPROB"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CMS.MERGE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.ADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.ALIASADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.ALIASUPDATE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.ALTER"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.CREATE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.DICTADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SUGADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SYNADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT.SYNUPDATE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._ALIASADDIFNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._ALTERIFNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FT._CREATEIFNX"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.ARRAPPEND"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.ARRINSERT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.MERGE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.MSET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.SET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.STRAPPEND"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("JSON.TOGGLE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.ADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.CREATE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.MERGE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TDIGEST.RESET"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.ADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.INCRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TOPK.RESERVE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.ADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.ALTER"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.CREATE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.DECRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.INCRBY"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.MADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("_FT.SAFEADD"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MODULE, CommandFlag.WRITE));

    // 6 command(s) with: denyoom, movablekeys, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEORADIUS"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("GEORADIUSBYMEMBER"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SORT"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZDIFFSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZINTERSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ZUNIONSTORE"), EnumSet.of(CommandFlag.DENYOOM, CommandFlag.MOVABLEKEYS, CommandFlag.WRITE));

    // 6 command(s) with: fast, loading, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ECHO"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("LASTSAVE"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("READONLY"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("READWRITE"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SELECT"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TIME"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.STALE));

    // 19 command(s) with: fast, module, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.CARD"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.DEBUG"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.EXISTS"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.INFO"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.MEXISTS"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("BF.SCANDUMP"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.COMPACT"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.COUNT"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.DEBUG"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.EXISTS"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.INFO"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.MEXISTS"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.SCANDUMP"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VCARD"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VDIM"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VEMB"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VGETATTR"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VINFO"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VLINKS"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.READONLY));

    // 3 command(s) with: fast, module, write
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("CF.DEL"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TS.CREATERULE"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.WRITE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("VSETATTR"), EnumSet.of(CommandFlag.FAST, CommandFlag.MODULE, CommandFlag.WRITE));

    // 3 command(s) with: module, noscript, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SEARCH.CLUSTERREFRESH"), EnumSet.of(CommandFlag.MODULE, CommandFlag.NOSCRIPT, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TIMESERIES.CLUSTERSET"), EnumSet.of(CommandFlag.MODULE, CommandFlag.NOSCRIPT, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("TIMESERIES.REFRESHCLUSTER"), EnumSet.of(CommandFlag.MODULE, CommandFlag.NOSCRIPT, CommandFlag.READONLY));

    // 2 command(s) with: admin, loading, noscript, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DEBUG"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MONITOR"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));

    // 3 command(s) with: admin, noscript, no_async_loading, no_multi
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PSYNC"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING, CommandFlag.NO_MULTI));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SAVE"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING, CommandFlag.NO_MULTI));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SYNC"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING, CommandFlag.NO_MULTI));

    // 2 command(s) with: admin, noscript, no_async_loading, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("REPLICAOF"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SLAVEOF"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.NOSCRIPT, CommandFlag.NO_ASYNC_LOADING, CommandFlag.STALE));

    // 1 command(s) with: fast, loading, noscript, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("ROLE"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));

    // 2 command(s) with: fast, loading, pubsub, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PUBLISH"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SPUBLISH"), EnumSet.of(CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.PUBSUB, CommandFlag.STALE));

    // 2 command(s) with: loading, module, noscript, readonly
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SEARCH.CLUSTERINFO"), EnumSet.of(CommandFlag.LOADING, CommandFlag.MODULE, CommandFlag.NOSCRIPT, CommandFlag.READONLY));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SEARCH.CLUSTERSET"), EnumSet.of(CommandFlag.LOADING, CommandFlag.MODULE, CommandFlag.NOSCRIPT, CommandFlag.READONLY));

    // 6 command(s) with: loading, noscript, pubsub, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PSUBSCRIBE"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("PUNSUBSCRIBE"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SSUBSCRIBE"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SUBSCRIBE"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SUNSUBSCRIBE"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.PUBSUB, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("UNSUBSCRIBE"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.PUBSUB, CommandFlag.STALE));

    // 1 command(s) with: loading, noscript, skip_slowlog, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EXEC"), EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.SKIP_SLOWLOG, CommandFlag.STALE));

    // 1 command(s) with: admin, allow_busy, loading, noscript, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("REPLCONF"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.ALLOW_BUSY, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));

    // 4 command(s) with: allow_busy, fast, loading, noscript, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("DISCARD"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("MULTI"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("UNWATCH"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("WATCH"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));

    // 3 command(s) with: movablekeys, noscript, no_mandatory_keys, skip_monitor, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EVAL"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.NOSCRIPT, CommandFlag.NO_MANDATORY_KEYS, CommandFlag.SKIP_MONITOR, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EVALSHA"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.NOSCRIPT, CommandFlag.NO_MANDATORY_KEYS, CommandFlag.SKIP_MONITOR, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FCALL"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.NOSCRIPT, CommandFlag.NO_MANDATORY_KEYS, CommandFlag.SKIP_MONITOR, CommandFlag.STALE));

    // 1 command(s) with: admin, allow_busy, loading, noscript, no_multi, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("SHUTDOWN"), EnumSet.of(CommandFlag.ADMIN, CommandFlag.ALLOW_BUSY, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.NO_MULTI, CommandFlag.STALE));

    // 4 command(s) with: allow_busy, fast, loading, noscript, no_auth, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("AUTH"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.NO_AUTH, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("HELLO"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.NO_AUTH, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("QUIT"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.NO_AUTH, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("RESET"), EnumSet.of(CommandFlag.ALLOW_BUSY, CommandFlag.FAST, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.NO_AUTH, CommandFlag.STALE));

    // 3 command(s) with: movablekeys, noscript, no_mandatory_keys, readonly, skip_monitor, stale
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EVALSHA_RO"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.NOSCRIPT, CommandFlag.NO_MANDATORY_KEYS, CommandFlag.READONLY, CommandFlag.SKIP_MONITOR, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("EVAL_RO"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.NOSCRIPT, CommandFlag.NO_MANDATORY_KEYS, CommandFlag.READONLY, CommandFlag.SKIP_MONITOR, CommandFlag.STALE));
    COMMAND_FLAGS_REGISTRY.put(SafeEncoder.encode("FCALL_RO"), EnumSet.of(CommandFlag.MOVABLEKEYS, CommandFlag.NOSCRIPT, CommandFlag.NO_MANDATORY_KEYS, CommandFlag.READONLY, CommandFlag.SKIP_MONITOR, CommandFlag.STALE));

  }

  /**
   * Get the flags for a given command. Flags are looked up from a static
   * registry based on the command arguments. This approach significantly reduces
   * memory usage by sharing flag instances across all CommandObject instances.
   * <p>
   * For commands with subcommands (e.g., FUNCTION LOAD, ACL SETUSER), this method
   * implements a hierarchical lookup strategy:
   * <ol>
   * <li>First, retrieve the parent command using CommandArguments.getCommand()</li>
   * <li>Check if this is a parent command (has subcommands in the registry)</li>
   * <li>If it is a parent command, attempt to get the child/subcommand by:
   *     <ul>
   *     <li>Extracting the second argument from the CommandArguments object</li>
   *     <li>Matching this second argument against the child items of the parent command</li>
   *     </ul>
   * </li>
   * <li>Return the appropriate flags based on whether a child command was found or just use the parent command's flags</li>
   * </ol>
   *
   * @param commandArguments the command arguments containing the command and its parameters
   * @return EnumSet of CommandFlag for this command, or empty set if command has no flags
   */
  @Override
  public EnumSet<CommandFlag> getFlags(CommandArguments commandArguments) {
    // Get the parent command
    ProtocolCommand cmd = commandArguments.getCommand();
    byte[] raw = cmd.getRaw();
    
    // Convert to uppercase using SafeEncoder utility (faster than String.toUpperCase())
    byte[] uppercaseBytes = SafeEncoder.toUpperCase(raw);

    // Look up the parent command in the registry using byte array key
    Object registryEntry = COMMAND_FLAGS_REGISTRY.get(uppercaseBytes);

    if (registryEntry == null) {
      // Command not found in registry
      return EMPTY_FLAGS;
    }

    // Check if this is a simple command (EnumSet) or a parent command with subcommands (SubcommandRegistry)
    if (registryEntry instanceof EnumSet) {
      // Simple command without subcommands
      return (EnumSet<CommandFlag>) registryEntry;
    } else if (registryEntry instanceof SubcommandRegistry) {
      // Parent command with subcommands
      SubcommandRegistry subcommandRegistry = (SubcommandRegistry) registryEntry;

      // Try to extract the subcommand from the second argument
      if (commandArguments.size() > 1) {
        Rawable secondArg = commandArguments.get(1);
        byte[] subRaw = secondArg.getRaw();
        
        // Convert to uppercase using SafeEncoder utility
        byte[] subUppercaseBytes = SafeEncoder.toUpperCase(subRaw);
        
        EnumSet<CommandFlag> subcommandFlags = subcommandRegistry.subcommands.get(subUppercaseBytes);
        if (subcommandFlags != null) {
          return subcommandFlags;
        }
      }

      // No subcommand found or no second argument, return parent flags
      return subcommandRegistry.parentFlags;
    }

    // Should not reach here, but return empty flags as fallback
    return EMPTY_FLAGS;
  }
}
