package redis.clients.jedis;

import static redis.clients.jedis.StaticCommandFlagsRegistry.*;
import java.util.EnumSet;

/**
 * Static initializer for StaticCommandFlagsRegistry. This class is auto-generated by
 * CommandFlagsRegistryGenerator. DO NOT EDIT MANUALLY.
 * <p>Generated from Redis Server:
 * <ul>
 * <li>Version: 8.2.3</li>
 * <li>Mode: standalone</li>
 * <li>Loaded Modules: ReJSON, timeseries, bf, vectorset, search</li>
 * <li>Generated at: 2025-11-04 13:00:13 CET</li>
 * </ul>
 */
final class StaticCommandFlagsRegistryInitializer {

  static void initialize(StaticCommandFlagsRegistry.Builder builder) {
    builder.register("ACL", EMPTY_FLAGS);
    builder.register("ACL", "CAT", EnumSet.of(CommandFlagsRegistry.CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    builder.register("ACL", "DELUSER", EnumSet.of(CommandFlag.ADMIN, CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
    builder.register("ACL", "GETUSER", EnumSet.of(CommandFlag.LOADING, CommandFlag.NOSCRIPT, CommandFlag.STALE));
  }

}
