name: Documentation Tests

on:
  push:
    branches:
      - master
      - 'emb-examples'
  pull_request:
  workflow_dispatch:

jobs:
  doctests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Cache dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: Set up Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Run doctests
        run: |
          mvn -Pdoctests clean compile test
