---

name: Publish Snapshot

on:
  push:
    branches:
      - master
      - '[0-9].x'
  workflow_dispatch:

jobs:

  snapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up publishing to maven central
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: mvn offline
        run: |
          mvn -q dependency:go-offline
      - name: deploy
        run: |
          mvn --no-transfer-progress \
            -DskipTests deploy
        env:
          MAVEN_USERNAME: ${{secrets.OSSH_USERNAME}}
          MAVEN_PASSWORD: ${{secrets.OSSH_TOKEN}}
